Lab 1
Onvix24/Max-Golonko-IPZ-31 pull request #1
Opened 2023-09-09 08:58 UTC by Onvix24

2023-09-09 09:06 UTC, vozniuk-lntu commented on index.html
> +        <div class="wrapper">
обгортка зайва

2023-09-09 09:27 UTC, vozniuk-lntu requested changes
видалити png

2023-09-09 09:27 UTC, vozniuk-lntu commented on index.html
> +                <div class="mainpage__container">
45, 46 не треба
49, 50, 51 тоже  не треба

2023-09-09 09:27 UTC, vozniuk-lntu commented on index.html
> +                                                    <div class="content-card__title">УВАГА ДО ДЕТАЛЕЙ</div>
тут заголовок

2023-09-09 09:27 UTC, vozniuk-lntu commented on index.html
> +                                <div class="card__body">
семантична розмітка

2023-09-09 09:27 UTC, vozniuk-lntu commented on index.html
> +                                        <div class="content-team__list">
семантично списком

2023-09-09 09:27 UTC, vozniuk-lntu commented on index.html
> +                                                    <div class="content-team__title">Ольга Рєпіна</div>
h3

2023-09-09 09:27 UTC, vozniuk-lntu commented on index.html
> +                                                    <div class="content-team__subtitle">Product Designer</div>
тут p

2023-09-09 09:27 UTC, vozniuk-lntu commented on index.html
> +                        <nav class="menu__body">
тут нав не треба, використати adress

2023-09-10 11:40 UTC, Onvix24 commented on index.html
> +        <div class="wrapper">
done

2023-09-11 14:59 UTC, vozniuk-lntu requested changes

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                                <a href="" class="menu__link"><span>Web</span>Studio</a>
webstudio не в нав

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                    <div>
не бачу сенсу в цьому діві

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                    <div class="header-welcome__item">
нащо тут два діва?
Допустимо один, щоб далі центрувати, ще один нащо
та і той один не треба, бо можна буде відцентрувати навішавши на секцію стилі

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                        <button class="header-welcome__botton button">
клас є а типу нема

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                <h2 style="visibility: hidden;">.</h2>
замість крапочки має бути заголовок
секція про переваги - заголовок "наші переваги"

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                <div class="card__content content-card">
нащо цей дів
ці сами класи на юл норм ідуть
list в основному вживається в класаб юл

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                            <img src="./src//img/work/1.jpg" alt="our-work-image-1">
а ширина де картинки?

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                <div class="work__content content-work">
чому дів це ж окрема секція

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                <div class="team__content content-team">
це секція

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                            <img src="./src/img/team/1.jpg" alt="image">
ширина

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                            <div class="menu__link"><span>Web</span>Studio</div>
це не в адрес

2023-09-11 14:59 UTC, vozniuk-lntu commented on index.html
> +                            <div class="menu__link"><a href="#">м. Київ, пр-т Лесі Українки, 26</a></div>
ссилку на адресу встав
і атрибут rel

2023-09-11 16:49 UTC, Onvix24 commented on index.html
> +                            <div class="menu__link"><a href="#">м. Київ, пр-т Лесі Українки, 26</a></div>
ну здається зробив все, що треба, перевірьте ще раз

2023-09-11 19:38 UTC, vozniuk-lntu approved these changes
апрув є, два коменти виправиш
також по коміту бачу що ти куски кода міняєш на куски
дуже схоже на ctrl+C ctrl+V
по ідеї там були точечні правки і мені відображати мало зміну в рядку а не зміну куска кода
ну то таке

зливай в мейн
перевір чи деплоїться
нову гілку з мейн робиш
наступна лаба
https://docs.google.com/document/d/1THT3lT1JlDAHJNTSdngiToexdVmUeLbE/edit?usp=sharing&ouid=104518963218417128491&rtpof=true&sd=true
і скрін як буде виглядати (працюєш суто з шрифтами та кольорами)
https://i.imgur.com/tniDQxh.png

2023-09-11 19:38 UTC, vozniuk-lntu commented on index.html
> +                <div>
ну і нащо тут цей дів
ти в когось це скопіював, чи шо?)
була така сама помилка десь

2023-09-11 19:38 UTC, vozniuk-lntu commented on index.html
> +                        <img src="./src/img/team/4.jpg" alt="image" width="270px">
пікселі тут не пишуться

2023-09-11 19:54 UTC, Onvix24 commented on index.html
> +                <div>
я все сам роблю я навіть не знаю в кого можна щось чекнуть

2023-09-11 19:54 UTC, Onvix24 commented on index.html
> +                        <img src="./src/img/team/4.jpg" alt="image" width="270px">
ок

2023-09-11 19:56 UTC, merged

2023-09-11 19:58 UTC, Onvix24 commented on index.html
> +                <div>
де була обгортка з першої версії яку забув видалити