Lab 2
Onvix24/Max-Golonko-IPZ-31 pull request #3
Opened 2023-09-12 15:08 UTC by Onvix24

2023-09-12 15:13 UTC, Onvix24 commented
✔

2023-09-14 15:15 UTC, Onvix24 commented
тут поки же все погано, це не кінцева версія

2023-09-16 09:45 UTC, vozniuk-lntu requested changes
line-height робити 1.36(em) або 136%

font-style: normal;
line-height: normal;
це глобальні властивості на боді

2023-09-16 09:45 UTC, vozniuk-lntu commented on src/css/style.css
> +.menu__link {
тут колір додати для посилання

2023-09-16 09:45 UTC, vozniuk-lntu commented on index.html
>                  <address class="footer__body">
адреса вся синя

2023-09-16 09:45 UTC, vozniuk-lntu commented on portfolio.html
> +                    <button class="filter-list__button" type="button">Усі</button>
на кнопках не той колір шрифта при ховері, і транзінина нема

2023-09-23 09:22 UTC, vozniuk-lntu approved these changes
1. font-style: normal; не треба вішати на елементи
2. hover вішається на елемент без псевдокласа. hover + focus
3. максимально забрати з елементів ті стилі, які можна глобально повісити на боді
4. використати CSS змінні

третя лаба https://docs.google.com/document/d/1Oeay7NWz9ltQyIij00fH-GLMeKd0Hec0/edit?usp=drive_link&ouid=104518963218417128491&rtpof=true&sd=true

2023-09-23 09:22 UTC, vozniuk-lntu commented on src/css/style.css
>      width: 200px;
прибрати габарити кнопки
ховер такий 188CE8

2023-09-23 09:42 UTC, merged